# /// script
# dependencies = [
#   "rich",
# ]
# ///
import re
import json
import argparse
import logging
from typing import List, Optional
from rich import print
from rich.padding import Padding

FILE_PATH = "/home/jairamir/.local/share/instructlab/datasets/full-sdg-hotels/skills_train_msgs_2025-03-27T20_45_10.jsonl"


def print_training_message(message: str, search_terms: List[str]):
    content = message["content"]

    if search_terms:
        for term in search_terms:
            content = highlight_term_in_text(term, content)

    print("\n")
    print("[bold blue]ROLE:[/bold blue]", message["role"])
    print("[bold green]CONTENT:[/bold green]\n")
    print(Padding(content, pad=(0, 0, 0, 4)))
    print("\n")
    print("=" * 150)


def get_total_messages(filename: str):
    with open(filename) as handle:
        return len(handle.readlines())


def print_messages(filename: str, search_terms: List[str], limit: int):
    num_messages = 0
    with open(filename) as handle:
        for line in handle:
            jsonline = json.loads(line)

            for message in jsonline["messages"]:
                lowercase_content = message["content"].lower()
                if all([term.strip().lower() in lowercase_content for term in search_terms]):
                    print_training_message(message, search_terms)
                    num_messages += 1
                    if num_messages >= limit:
                        return num_messages

    return num_messages


def highlight_term_in_text(search_term: str, text: str):
    search_term = search_term.strip()
    pattern = re.compile(re.escape(search_term), re.IGNORECASE)

    highlighted_text = pattern.sub(lambda m: f"[bold italic red]{m.group(0)}[/bold italic red]", text)

    return highlighted_text


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="Syntetic data inspector",
        description=(
            'Inspects synthetic data generated by "ilab". '
            'Intended to be used with "skills_train*.jsonl" and "knowledge_train*.jsonl" files under ~/.local/share/instructlab/datasets/'
        ),
    )
    parser.add_argument("filename")
    parser.add_argument(
        '-s', '--search',
        dest='search_terms',
        action='append',
        help='Search messages containing the provided term (use multiple -s for multiple terms)'
    )
    parser.add_argument(
        "-l", "--limit", help="Limit the number of displayed messages", default=100
    )

    args = parser.parse_args()
    filename = args.filename
    limit = int(args.limit) if args.limit is not None else int("inf")
    search_terms = args.search_terms or []

    if not args.filename.endswith(".jsonl"):
        logging.fatal("The provided file must be in JSONL format")
        exit(1)

    num_messages = print_messages(filename, search_terms, limit)

    print("Total messages", get_total_messages(filename))
    print("Displayed messages", num_messages)
